framework:
    default_locale: "%env(LOCALE)%"
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - "en"

bazinga_js_translation:
    default_domain: js
    active_locales:
        - fr
        - en
