###########################
# Development environment #
#    DON'T USE IN PROD    #
###########################
version: '3.1'
services:
############
# DATABASE #
############
  db:
    container_name: battleship-db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: battleship
    volumes:
      - "./dev-docker-persist/mysql:/var/lib/mysql"
    ports:
      - "3307:3306"

###########
# MERCURE #
###########
  mercure:
    container_name: mercure
    image: dunglas/mercure
    environment:
      JWT_KEY: 'aVerySecretKey'
      ALLOW_ANONYMOUS: 1
      CORS_ALLOWED_ORIGINS: 'http://localhost:8000'
    ports:
    - "3000:80"
