###########################
# Development environment #
###########################
version: '3.1'
services:
############
# DATABASE #
############
  db:
    container_name: battleship-db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: battleship
    volumes:
      - "./dev-docker-persist/mysql:/var/lib/mysql"
    ports:
      - "3307:3306"

